'use client'

import '../styled/global.css'
import { ApolloProvider } from '@apollo/client';
import { client } from '../lib/API';

// export const metadata = {
//   title: "Next.js",
//   description: "Generated by Next.js",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
        <ApolloProvider client={client}>
          <div>{children}</div>
        </ApolloProvider>
      </body>
    </html>
  );
}
