'use client'

import { Box } from "@mui/material";
import "../styled/global.css";
import { ApolloProvider } from '@apollo/client'
import { client } from "../lib/API";

// export const metadata = {
//   title: "Next.js",
//   description: "Generated by Next.js",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
        <ApolloProvider client={client}>
          <Box
            sx={{
              backgroundImage: `url('loginBackground.svg')`,
              backgroundSize: "cover",
              backgroundRepeat: "no-repeat",
            }}
          >
            {children}
          </Box>
        </ApolloProvider>
      </body>
    </html>
  );
}
